name: rocketchip
channels:
  - anaconda
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.5.2
  - bwa=0.7.17
  - deeptools=3.5.4
  - fastqc=0.12.1
  - genrich=0.6.1
  - pepr=1.1.24
  - picard=3.1.1
  - pip==23.3.1
  - pyyaml=6.0.1
  - sambamba=1.0.0
  - samtools=1.18
  - snakemake-minimal=7.32.4
  - sra-tools=3.0.9
  - star=2.7.11a
  - pip:
    - macs3==3.0.0b3
